name: Profile cbds with grad 01, 6x, small, s2mpj

on:
  # Trigger the workflow on push or pull request
  # push:
  # Trigger the workflow manually
  # schedule:
  # - cron: '0 6 */1 * *'
  workflow_dispatch:

jobs:
  test:
    name: Profile cbds with grad 01, tol 06, small, s2mpj
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [R2024b]
        dim: [small]
        plibs: [s2mpj]
        with_optim_toolbox: [yes]
        feature: [plain, perturbed_x0_0.001, perturbed_x0_1, perturbed_x0_10, perturbed_x0_100, noisy_1e-1, noisy_1e-2, noisy_1e-3, noisy_1e-4, permuted, linearly_transformed, rotation_noisy_1e-1, rotation_noisy_1e-2, rotation_noisy_1e-3, rotation_noisy_1e-4]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Checkout OptiProfiler
        uses: actions/checkout@v4
        with:
          repository: optiprofiler/optiprofiler
          path: optiprofiler
          ref: 675a7cd5d52f1dbb7f5fdd486406b285dc6a8bc6

      - name: Install Texlive
        run: sudo apt-get update && sudo apt-get install texlive

      - name: Check whether LaTeX is installed
        run: pdflatex --version

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}-${{ matrix.with_optim_toolbox }}

      - name: Set up MATLAB with optimization toolbox
        if: ${{ matrix.with_optim_toolbox == 'yes' }}
        uses: matlab-actions/setup-matlab@v2.1.2
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox

      - name: Run test
        uses: matlab-actions/run-command@v2.1.1
        with:
            command: |
              root_dir = pwd()
              ls
  
              % Setup optiprofiler
              cd(fullfile(root_dir, 'optiprofiler'));
              setup(struct('install_matcutest', true));
              cd(root_dir);
  
              % Setup bds
              setup
              cd(fullfile(root_dir, 'tests', 'competitors'));
              addpath(pwd);
  
              % profile
              addpath(fullfile(root_dir, 'tests'));
              cd(fullfile(root_dir, 'tests', 'tuning'));
              parameters.grad_window_size = [1 1e8];
              parameters.grad_tol = [1e-6 1e-30];
              options = struct();
              options.solver_names = {'cbds-tuning-grad', 'cbds-default'};
              options.plibs = '${{ matrix.plibs }}';
              options.dim = '${{ matrix.dim }}';
              options.feature_name = '${{ matrix.feature }}';
              tuning_optiprofiler(parameters, options);
              cd(root_dir);

      - name: Change the summary file name
        run: |
          cd ./tests/tuning/tuning_data
          ls -R
          find . -type f -name 'summary.pdf' | while read -r file; do
            # Obtain the parent directory and name
            parent_dir=$(dirname "$file")
            parent_name=$(basename "$parent_dir")

            # Obtain the new name(Why the fifth underline? Because the last five parts are the time stamp)
            new_name=$(echo "$parent_name" | awk -F'_' '{if(NF>=5) {for(i=1;i<=NF-5;i++) printf "%s%s", $i, (i<NF-5?"_":"")} else print $0}')

            # Print the new name
            echo "New name: $new_name"

            # Obtain the directory name
            dir_name=$(dirname "$file")
            
            # Establish the new file name
            new_file="$dir_name/summary_$new_name.pdf"
            
            # Check if the source and destination are the same
            if [ "$file" != "$new_file" ]; then
              mv "$file" "$new_file"
              echo "Renamed $file to $new_file"
            else
              echo "Source and destination are the same, skipping: $file"
            fi
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: profile_optiprofiler_cbds_func_window_size_01_tol_06_${{ matrix.plibs }}_${{ matrix.dim }}_${{ matrix.feature }}
          path: ./tests/tuning/tuning_data/**

  merge_artifacts:
    name: Merge Artifacts
    runs-on: ubuntu-latest
    needs: test
    permissions:
      actions: read
      contents: read
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install PDF tools
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: tests/tuning/tuning_data/downloaded_artifacts

      - name: List all files
        run: |
          cd tests/tuning/tuning_data/downloaded_artifacts
          ls -R

      - name: Merge PDF files
        run: |
          cp tests/tools/merge_pdf.sh tests/tuning/tuning_data/downloaded_artifacts
          cd tests/tuning/tuning_data/downloaded_artifacts/

          ARTIFACT_NAME=$(ls | grep "profile_optiprofiler" | head -n 1)
          BASE_INFO=$(echo $ARTIFACT_NAME | sed -n 's/.*optiprofiler_\([^_]*_[^_]*_\(small\|big\|large\)\).*/\1/p')

          # Replace all '-' with '_' in BASE_INFO
          BASE_INFO=$(echo $BASE_INFO | sed 's/-/_/g')
          echo "Base info extracted: ${BASE_INFO}"
          echo "BASE_INFO=${BASE_INFO}" >> $GITHUB_ENV

          # Merge PDF files
          mkdir summary
          for f in $(find . -maxdepth 3 -type f -name 'summary*.pdf'); do
              if [ ! -f "summary/$(basename $f)" ]; then
                  cp "$f" summary/
              fi
          done
          
          cd summary
          ls
          bash ../merge_pdf.sh
          mv merged.pdf "summary_cbds_func_window_size_01_tol_06_small_s2mpj.pdf"
          cd ..
          if [ -d "summary" ]; then
            mv summary "summary_cbds_func_window_size_01_tol_06_small_s2mpj"
          fi

      - name: Upload merged artifact
        uses: actions/upload-artifact@v4
        env:
          BASE_INFO: ${{ env.BASE_INFO }}
        with:
          name: merged_profiles_cbds_func_window_size_01_tol_06_small_s2mpj
          path: tests/tuning/tuning_data/downloaded_artifacts/**

      - name: Upload summary files
        uses: actions/upload-artifact@v4
        env:
          BASE_INFO: ${{ env.BASE_INFO }}
        with:
          name: summary_files_cbds_func_window_size_01_tol_06_small_s2mpj
          path: tests/tuning/tuning_data/downloaded_artifacts/summary_cbds_func_window_size_01_tol_06_small_s2mpj/**