name: Profile original cbds termination with simplified cbds, small, matcutest
on:
  # Trigger the workflow on push or pull request
  # push:
  # Trigger the workflow manually
  # schedule:
  # - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  test:
    name: Profile original cbds termination with simplified cbds, small, matcutest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [latest]
        dim: [small]
        with_optim_toolbox: [yes]
        solver: [cbds-orig-termination]
        competitor: [cbds-simplified]
        plibs: [matcutest]
        run_plain: [false]
        summarize_log_ratio_profiles: [false]
        feature: [plain, perturbed_x0_0.001, perturbed_x0_1, perturbed_x0_10, perturbed_x0_100, noisy_1e-1, noisy_1e-2, noisy_1e-3, noisy_1e-4, truncated_1, truncated_2, truncated_3, truncated_4, permuted, linearly_transformed, random_nan_5, random_nan_10, random_nan_20, quantized_1, quantized_2, quantized_3, quantized_4, rotation_noisy_1e-1, rotation_noisy_1e-2, rotation_noisy_1e-3, rotation_noisy_1e-4]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout OptiProfiler
        uses: actions/checkout@v4
        with:
          repository: optiprofiler/optiprofiler
          path: optiprofiler
          ref: 675a7cd5d52f1dbb7f5fdd486406b285dc6a8bc6

      - name: Install Texlive
        run: sudo apt-get update && sudo apt-get install texlive

      - name: Check whether LaTeX is installed
        run: pdflatex --version

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}-${{ matrix.with_optim_toolbox }}

      - name: Set up MATLAB with optimization toolbox
        if: ${{ matrix.with_optim_toolbox == 'yes' }}
        uses: matlab-actions/setup-matlab@v2.1.2
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox

      - name: Run test
        uses: matlab-actions/run-command@v2.1.1
        with:
            command: |
              root_dir = pwd()
              ls
  
              % Setup optiprofiler
              cd(fullfile(root_dir, 'optiprofiler'));
              setup(struct('install_matcutest', true));
  
              % Setup bds
              cd(root_dir);
              setup
              cd(fullfile(root_dir, 'tests', 'competitors'));
              addpath(pwd);
  
              % profile
              cd(fullfile(root_dir, 'tests'));
              options = struct();
              options.feature_name = '${{ matrix.feature }}';
              options.solver_names = {'${{ matrix.solver }}', '${{ matrix.competitor }}'};
              options.dim = '${{ matrix.dim }}';
              options.plibs = '${{ matrix.plibs }}';
              options.run_plain = ${{ matrix.run_plain }};
              options.summarize_log_ratio_profiles = ${{ matrix.summarize_log_ratio_profiles }};
              profile_optiprofiler(options);
              cd(fullfile(root_dir, 'tests'));
              ls -R
              cd(root_dir);

      - name: Change the summary file name
        run: |
          cd ./tests/testdata/
          ls -R
          find . -type f -name 'summary.pdf' | while read -r file; do
            # Obtain the parent directory and name
            parent_dir=$(dirname "$file")
            parent_name=$(basename "$parent_dir")

            # Obtain the new name(Why the fifth underline? Because the last five parts are the time stamp)
            new_name=$(echo "$parent_name" | awk -F'_' '{if(NF>=5) {for(i=1;i<=NF-5;i++) printf "%s%s", $i, (i<NF-5?"_":"")} else print $0}')

            # Print the new name
            echo "New name: $new_name"

            # Obtain the directory name
            dir_name=$(dirname "$file")
            
            # Establish the new file name
            new_file="$dir_name/summary_$new_name.pdf"
            
            # Check if the source and destination are the same
            if [ "$file" != "$new_file" ]; then
              mv "$file" "$new_file"
              echo "Renamed $file to $new_file"
            else
              echo "Source and destination are the same, skipping: $file"
            fi
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        env:
          BASE_INFO: ${{ env.BASE_INFO }}
        with:
          name: merged_profiles_${{ env.BASE_INFO }}
          path: tests/testdata/downloaded_artifacts/**

      - name: Upload summary files
        uses: actions/upload-artifact@v4
        env:
          BASE_INFO: ${{ env.BASE_INFO }}
        with:
          name: summary_files_${{ env.BASE_INFO }}
          path: tests/testdata/downloaded_artifacts/summary_${{ env.BASE_INFO }}/**
